"""
This type stub file was generated by pyright.
"""

from typing import Dict, Union
from pinecone.core.client.models import SparseValues

class SparseValuesFactory:
    @staticmethod
    def build(input: Union[Dict, SparseValues]) -> SparseValues:
        ...
    


