# TODO: Work with team to see when the right time is to enable this
# # exclude: '^src/validate_pyproject/_vendor'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Simply check whether files parse as valid python.
      - id: check-ast
        exclude: (.vscode|contrib)
      - id: check-json
        exclude: (.vscode|.devcontainer|hack)

  # SOURCE: https://github.com/astral-sh/ruff-pre-commit
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      # Run the linter.
      - id: ruff
        # entry: ruff check --force-exclude
        args: [--fix, --exit-non-zero-on-fix, --show-fixes, --config=pyproject.toml]

      # Run the formatter.
      - id: ruff-format
        # entry: ruff format --force-exclude
        args: [--config=pyproject.toml]
        files: ^((src|hack)/.+)?[^/]+\.(py|pyi)$



  # NOTE: This requires you to brew install taplo
  - repo: local
    hooks:
      - id: taplo
        name: taplo
        entry: taplo format --config taplo.toml
        language: system
        types: [toml]
        files: "^pyproject.*$"
