# TODO: Work with team to see when the right time is to enable this
# # exclude: '^src/validate_pyproject/_vendor'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # Simply check whether files parse as valid python.
      - id: check-ast
        exclude: (.vscode|contrib)
      - id: check-json
        exclude: (.vscode|.devcontainer|hack)

  # SOURCE: https://github.com/Ruzzy77/python-template/blob/57c8964f1efb2635d0bdca5684613a8d8736aed0/.pre-commit-config.yaml
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: "v3.0.3"
  #   hooks:
  #       - id: prettier
  #         # types_or: [json, yaml]
  #         exclude_types: [markdown, python, toml]
  #         args:
  #             [
  #                 "--config",
  #                 ".prettierrc",
  #                 "--write",
  #                 "--ignore-path",
  #                 ".prettierignore",
  #                 "--ignore-unknown",
  #             ]
  #         # additional_dependencies: ["prettier", "prettier-plugin-multiline-arrays"]
  # SOURCE: https://github.com/astral-sh/ruff-pre-commit
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      # Run the linter.
      - id: ruff
        # entry: ruff check --force-exclude
        args: [--fix, --exit-non-zero-on-fix, --show-fixes, --config=pyproject.toml]

      # Run the formatter.
      - id: ruff-format
        # entry: ruff format --force-exclude
        args: [--config=pyproject.toml]
        files: ^((src|tests)/.+)?[^/]+\.(py|pyi)$
        exclude: (.tasks|hack)

  # SOURCE: https://github.com/Ruzzy77/python-template/blob/57c8964f1efb2635d0bdca5684613a8d8736aed0/.pre-commit-config.yaml
  # - repo: https://github.com/pre-commit/mirrors-prettier
  # - repo: https://github.com/PyCQA/docformatter
  #   rev: v1.7.5
  #   hooks:
  #       - id: docformatter
  #         additional_dependencies: [tomli]
  #         args: ["--in-place", "--recursive", "--diff", "."]


  # NOTE: This requires you to brew install taplo
  - repo: local
    hooks:
      - id: taplo
        name: taplo
        entry: taplo format --config taplo.toml
        language: system
        types: [toml]
        files: "^pyproject.*$"
