"""
This type stub file was generated by pyright.
"""

__all__ = ['Anderson', 'BroydenFirst', 'BroydenSecond', 'DiagBroyden', 'ExcitingMixing', 'GenericBroyden', 'InverseJacobian', 'Jacobian', 'KrylovJacobian', 'LinAlgError', 'LinearMixing', 'LowRankMatrix', 'NoConvergence', 'TerminationCondition', 'anderson', 'asarray', 'asjacobian', 'broyden1', 'broyden2', 'diagbroyden', 'dot', 'excitingmixing', 'get_blas_funcs', 'inspect', 'inv', 'linearmixing', 'maxnorm', 'newton_krylov', 'nonlin_solve', 'norm', 'qr', 'scalar_search_armijo', 'scalar_search_wolfe1', 'scipy', 'solve', 'svd', 'sys', 'vdot']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any | None:
    ...

