"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from ...utils import OptionalDependencyNotAvailable, _LazyModule, is_tokenizers_available, is_vision_available
from .processing_nougat import NougatProcessor

_import_structure = ...
if not is_tokenizers_available():
    ...
if not is_vision_available():
    ...
if TYPE_CHECKING:
    ...
else:
    ...
