"""
This type stub file was generated by pyright.
"""

__all__ = ['LinearOperator', 'aslinearoperator', 'isshape', 'isintlike', 'asmatrix', 'is_pydata_spmatrix', 'MatrixLinearOperator', 'IdentityOperator']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any | None:
    ...

