"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from ...utils import OptionalDependencyNotAvailable, _LazyModule, is_torch_available
from .configuration_x_clip import XCLIPConfig, XCLIPTextConfig, XCLIPVisionConfig, XCLIP_PRETRAINED_CONFIG_ARCHIVE_MAP
from .processing_x_clip import XCLIPProcessor

_import_structure = ...
if not is_torch_available():
    ...
if TYPE_CHECKING:
    ...
else:
    ...
