"""
This type stub file was generated by pyright.
"""

from typing import Dict, Union
from pinecone.core.grpc.protos.vector_service_pb2 import SparseValues as GRPCSparseValues
from pinecone import SparseValues as NonGRPCSparseValues

class SparseValuesFactory:
    @staticmethod
    def build(input: Union[Dict, GRPCSparseValues, NonGRPCSparseValues]) -> GRPCSparseValues:
        ...
    


