"""
This type stub file was generated by pyright.
"""

from ..utils import DummyObject

class MusicgenMelodyFeatureExtractor(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class MusicgenMelodyProcessor(metaclass=DummyObject):
    _backends = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    


