# name: GitHub Actions CI
# on:
#   push:
#     branches:
#       - main
#       - master
#   pull_request:
# jobs:
#   style:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Set up Git repository
#         uses: actions/checkout@main

#   tests:
#     name: Test against latest release
#     strategy:
#       matrix:
#         # shell: [fish, zsh, bash]
#         setup:
#           - os: ubuntu-22.04
#             script_arguments: ''

#     runs-on: ${{ matrix.setup.os }}
#     steps:
#       - name: Set up Git repository
#         uses: actions/checkout@main

#       - run: bin/zsh-dotfiles-prereq-installer
#         env:
#           ZSH_DOTFILES_PREP_CI: 1
#           ZSH_DOTFILES_PREP_DEBUG: 1
#           # NOTE: Skip Brew bundle for now, speed up tests
#           ZSH_DOTFILES_PREP_GITHUB_USER: bossjones
#           ZSH_DOTFILES_PREP_SKIP_BREW_BUNDLE: 1

#       - name: Rerun bin/zsh-dotfiles-prereq-installer
#         run: bin/zsh-dotfiles-prereq-installer
#         env:
#           ZSH_DOTFILES_PREP_CI: 1
#           ZSH_DOTFILES_PREP_GITHUB_USER: bossjones
#           ZSH_DOTFILES_PREP_SKIP_BREW_BUNDLE: 1


#       - run: brew config
#         if: matrix.setup.os == 'macos-12'

#       - run: brew cleanup || true
#         if: matrix.setup.os == 'macos-12'
#         continue-on-error: true

#       - run: brew doctor || true
#         if: matrix.setup.os == 'macos-12'
#         continue-on-error: true

#       - name: Install Ruby dependencies
#         run: brew install gmp openssl@1.1 libyaml openssl@3
#         if: matrix.setup.os == 'macos-12'

# # -----------------------------------------
# # name: Check Pull Request

# # on:
# #   pull_request:
# #     types: [opened, synchronize, reopened]

# # jobs:
# #   check-pull-request:
# #     runs-on: ubuntu-latest
# #     steps:
# #       - name: Checkout
# #         uses: actions/checkout@v3
# #         with:
# #           ref: ${{ github.head_ref }}
# #       - name: Install Rye
# #         uses: baptiste0928/cargo-install@v2
# #         with:
# #           crate: rye
# #           git: https://github.com/mitsuhiko/rye
# #           branch: main
# #       - name: Install Dependencies
# #         run: rye sync
# #       - name: Lint
# #         run: rye run lint
# #       - name: Test
# #         run: rye run test
