---
# SOURCE: https://github.com/astral-sh/rye/blob/4b34ca16ac06794640c86a82ccd8ccd7b124a0ad/.github/workflows/docs.yml
name: Publish docs via GitHub Pages
on: # yamllint disable-line rule:truthy
    push:
        paths: ['docs/**', 'CHANGELOG.md', 'mkdocs.yml', 'scripts/install.sh']
        branches:
            - main
  # # https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_dispatch
  # workflow_dispatch:
  #   # Allow this workflow to be run manually (pushing to testpypi instead of pypi)
    workflow_dispatch:
        inputs:
            debug_enabled:
                description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
                required: false
                default: false
jobs:
    build:
        if: github.repository == 'astral-sh/rye'
        name: Deploy docs
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main
              uses: actions/checkout@v2
            - uses: Swatinem/rust-cache@v2
      # - name: Deploy docs
      #   uses: mhausenblas/mkdocs-deploy-gh-pages@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     CONFIG_FILE: mkdocs.yml
      #     REQUIREMENTS: ./requirements.lock
      # Allow debugging with tmate
            - name: Setup tmate session
              uses: mxschmitt/action-tmate@v3
              if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
              with:
                  limit-access-to-actor: true
